version: '3'

services:
    web:
        build: .
        env_file:
            - .env
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - DATABASE_URL=${DATABASE_URL}
        command: gunicorn -b 0.0.0.0:8080 -c guniconfig.py engine.wsgi:application
        ports:
            - "8080:8080"
        volumes:
            - .:/code
